In [7]:
import warnings
warnings.filterwarnings('ignore')

In [8]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [9]:
# Load data from database export
file_path = "Database/collision_data_ml.csv"
ml_df = pd.read_csv(file_path)
ml_df

,accident_year,collision_time,day_of_week,weather_1,primary_coll_factor,type_of_collision,road_surface,road_cond_1,lighting,point_x,...,party_safety_equip_1,party_safety_equip_2,oaf_1,party_number_killed,party_number_injured,move_pre_acc,vehicle_year,vehicle_make,stwd_vehicle_type,race
0,2017,1955,7,A,A,B,A,H,C,-118.280930,...,M,G,N,0,2,B,2012,HONDA,A,B
1,2017,1955,7,A,A,B,A,H,C,-118.280930,...,L,G,N,0,1,J,2017,BMW,A,B
2,2017,1500,6,A,A,A,A,H,C,-118.255930,...,M,G,N,0,0,D,2013,TOYOTA,A,H
3,2017,1010,3,A,A,D,A,H,A,-118.315700,...,L,G,N,0,1,E,2006,TOYOTA,A,W
4,2017,1010,3,A,A,D,A,H,A,-118.315700,...,L,G,A,0,0,B,2017,HONDA,A,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270465,2019,1920,5,A,A,C,A,H,D,-118.419853,...,M,G,N,0,1,H,2017,NISS,A,O
270466,2019,1920,5,A,A,C,A,H,D,-118.419853,...,M,G,N,0,0,A,2010,TOYT,A,O
270467,2019,1920,5,A,A,C,A,H,D,-118.419853,...,M,G,N,0,0,A,2016,ACUR,A,O
270468,2019,115,5,B,A,D,A,H,C,-118.376869,...,L,G,A,0,3,E,2003,HYUN,A,H
270469,2019,115,5,B,A,D,A,H,C,-118.376869,...,L,G,A,0,0,B,2018,MAZD,A,H

In [10]:
ml_df.dtypes[ml_df.dtypes != 'int64'][ml_df.dtypes != 'float64']

weather_1               object
primary_coll_factor     object
type_of_collision       object
road_surface            object
road_cond_1             object
lighting                object
at_fault                object
party_sex               object
party_soberiety         object
party_safety_equip_1    object
party_safety_equip_2    object
oaf_1                   object
move_pre_acc            object
vehicle_make            object
stwd_vehicle_type       object
race                    object
dtype: object

In [12]:
# Convert strings to numeric values
from sklearn.preprocessing import LabelEncoder
ml_df_encoded = pd.get_dummies(ml_df, columns=["weather_1","primary_coll_factor", "type_of_collision", "road_surface", 
                                                   "road_cond_1", "lighting", "at_fault", "party_sex", 
                                                   "party_soberiety", "party_safety_equip_1", "party_safety_equip_2",
                                           "oaf_1", "move_pre_acc", "vehicle_make", "stwd_vehicle_type", "race"])
ml_df_encoded.head()

,accident_year,collision_time,day_of_week,point_x,point_y,party_number,party_age,party_number_killed,party_number_injured,vehicle_year,...,stwd_vehicle_type_K,stwd_vehicle_type_L,stwd_vehicle_type_M,stwd_vehicle_type_N,stwd_vehicle_type_O,race_A,race_B,race_H,race_O,race_W
0,2017,1955,7,-118.28093,34.009389,1,29,0,2,2012,...,0,0,0,0,0,0,1,0,0,0
1,2017,1955,7,-118.28093,34.009389,2,53,0,1,2017,...,0,0,0,0,0,0,1,0,0,0
2,2017,1500,6,-118.25593,34.022390,1,37,0,0,2013,...,0,0,0,0,0,0,0,1,0,0
3,2017,1010,3,-118.31570,34.083510,1,34,0,1,2006,...,0,0,0,0,0,0,0,0,0,1
4,2017,1010,3,-118.31570,34.083510,2,18,0,0,2017,...,0,0,0,0,0,0,0,1,0,0